// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace EntityFrameworkCoreImages.Models
{
    public partial class Categories
    {
        /// <summary>
        /// Primary key
        /// </summary>
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
    }
}